name: Trigger Pull App Sync

on:
  schedule:
    - cron: '30 7 * * *'  # Täglich um 07:30 UTC – passe die Zeit ggf. an deine Zeitzone an
  workflow_dispatch:     # Erlaubt auch manuelles Triggern über die GitHub-Oberfläche

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pull App Sync
        run: |
          curl -L https://pull.git.ci/process/cippgrotheit/CIPP-API
